# Use this in your UnturnedImages/config.yaml file
- Id: "2050-2051;20542054;2060-2061;12028-12029;1205512055;25000" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1118504684/items/{ItemId}.png" # The repository of the override.