# Use this in your UnturnedImages/config.yaml file
- Id: "58005-58010" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3139756583/items/{ItemId}.png" # The repository of the override.