# Use this in your UnturnedImages/config.yaml file
- Id: "48601-48622" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2202393257/items/{ItemId}.png" # The repository of the override.